apiVersion: v1
kind: Service
metadata:
  name: knr-api
  labels:
    app: knr-api
spec:
  ports:
    - port: 8081
      targetPort: 80
      name: knr-api
  selector:
    app: knr-api
  type: LoadBalancer

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: knr-api
  labels:
    app: knr-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: knr-api
  template:
    metadata:
      labels:
        app: knr-api
    spec:
      containers:
      - name: knr-api
        image: knr-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m # i.e. one hundred millicores
            memory: 250Mi # i.e. 250 MiB
        volumeMounts:
        - mountPath: /root/api
          name: api-volume
        command:
          - /root/api/docker/entrypoint.sh
      volumes:
      - name: api-volume
        hostPath:
          path: //c/code/personal/kube-node-react/projects/api

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: knr-api
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: knr-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 125Mi
