apiVersion: v1
kind: Service
metadata:
  name: knr-frontend
  labels:
    app: knr-frontend
spec:
  ports:
    - port: 8082
      targetPort: 80
      name: knr-api-http
    - port: 8083
      targetPort: 8083
      name: knr-api-ws
  selector:
    app: knr-frontend
  type: LoadBalancer

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: knr-frontend
  labels:
    app: knr-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knr-frontend
  template:
    metadata:
      labels:
        app: knr-frontend
    spec:
      containers:
      - name: knr-frontend
        image: knr-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m # i.e. one hundred millicores
            memory: "250Mi" # i.e. 250 MiB
        volumeMounts:
        - mountPath: /root/frontend
          name: frontend-volume
        command:
          - /root/frontend/docker/entrypoint.sh
      volumes:
      - name: frontend-volume
        hostPath:
          path: //c/code/personal/kube-node-react/projects/frontend
